services:
  chown:
    image: alpine:3.16
    command:
      - /bin/sh
      - -c
      # Early creates the log file so wasm-logs does not fail even if envoy is not yet healthy
      - touch /home/envoy/logs/envoy.log && chown -R 101:101 /home/envoy/logs
    volumes:
      - logs:/home/envoy/logs:rw
  envoy:
    depends_on:
      - chown
    image: ${ENVOY_IMAGE:-envoyproxy/envoy:v1.28-latest}
    command:
      - -c
      - /conf/envoy-config.yaml
      - --log-level
      - info
      - --log-format [%Y-%m-%d %T.%f][%t][%l][%n] [%g:%#] %v
      - --log-path
      - /home/envoy/logs/envoy.log
    volumes:
      - ./build:/build
      - .:/conf
      - logs:/home/envoy/logs:rw
    ports:
    - 8080:8080
    - 8082:8082
  envoy-logs:
    depends_on:
      - envoy
    image: debian:11-slim
    entrypoint: bash
    command:
      - -c
      - tail -c +0 -f /home/envoy/logs/envoy.log > /build/envoy.log
    volumes:
      - logs:/home/envoy/logs:ro
      - ./build:/build
volumes:
  logs:
