name: CI
on:
  push:
    branches:
      - main
    tags:
      - "*"
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-12
          - ubuntu-22.04
          - windows-2022
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '^1.20.0'
          cache: true

      - name: setup tinygo
        uses: acifani/setup-tinygo@v1
        with:
          tinygo-version: 0.27.0
      - name: setup wasmtime for tinygo
        run: go install github.com/wasilibs/tools/cmd/wasmtime@c93d2e477ab3c1eb7f5303c66a35c84a21d06dbd

      - run: go run mage.go check
  build-tinygodev:
    runs-on: ubuntu-22.04
    container: ghcr.io/tinygo-org/tinygo/tinygo-dev:sha-f6df2761187f1975e35eb43461d735d6e325df85
    steps:
      - uses: actions/checkout@v3

      - run: |
          go install github.com/wasilibs/tools/cmd/wasmtime@c93d2e477ab3c1eb7f5303c66a35c84a21d06dbd
          go run mage.go test
        env:
          GOFLAGS: -buildvcs=false
