name: E2E Tests
on:
  push:
    branches:
      - main
  pull_request:
  schedule:
    # https://crontab.guru/#5_2_*_*_*
    - cron: '5 2 * * *'
  workflow_dispatch:

jobs:
  e2e:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        target:
          - coraza
          - envoyDispatchCall
          - higressGCTest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: '^1.20.0'

      - name: setup tinygo
        uses: acifani/setup-tinygo@v1
        with:
          tinygo-version: 0.30.0

      - run: go run mage.go e2e${{ matrix.target }}

      - uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: ${{ matrix.target }}-logs
          path: build/logs/
